# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MkHkLIfFjMFKsH9YlVsF5Cgy71wNjOeH
"""

import numpy as np
import matplotlib.pyplot as plt

# === CONFIGURACIÓN DE LA CURVA BÉZIER ===
# Puntos de control (modifica estos si lo deseas)
P0 = np.array([0.8, 0.5])
P1 = np.array([0.5, 0.5])
P2 = np.array([0.5, 0.8])
P3 = np.array([0.5, 1.0])

# Función para curva Bézier cúbica
def bezier_cubic(t, P0, P1, P2, P3):
    return (1 - t)**3 * P0 + 3 * (1 - t)**2 * t * P1 + 3 * (1 - t) * t**2 * P2 + t**3 * P3

# === GENERACIÓN DE PUNTOS ===
T = np.linspace(0, 1, 50)  # Ajusta la cantidad de puntos si lo deseas
curve = np.array([bezier_cubic(t, P0, P1, P2, P3) for t in T])

# === GUARDAR COMO ARCHIVO .h ===
header_file = "bezier_points.h"

with open(header_file, "w") as f:
    f.write("#ifndef BEZIER_POINTS_H\n")
    f.write("#define BEZIER_POINTS_H\n\n")
    f.write("const int N_POINTS = {};\n".format(len(curve)))
    f.write("const float bezier_x[] = {")
    f.write(", ".join("{:.6f}".format(p[0]) for p in curve))
    f.write("};\n")
    f.write("const float bezier_y[] = {")
    f.write(", ".join("{:.6f}".format(p[1]) for p in curve))
    f.write("};\n\n")
    f.write("#endif\n")

print(f"Archivo '{header_file}' generado con éxito.")

# === GRAFICAR LA CURVA ===
plt.plot(curve[:, 0], curve[:, 1], label="Curva Bézier")
plt.plot([P0[0], P1[0], P2[0], P3[0]], [P0[1], P1[1], P2[1], P3[1]], 'ro--', label="Puntos de control")
plt.xlabel("x")
plt.ylabel("y")
plt.title("Curva Bézier Cúbica")
plt.legend()
plt.grid(True)
plt.axis("equal")
plt.show()

